name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Enable Corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.10.0 --activate
          pnpm -v

      - name: Install dependencies (workspace)
        run: pnpm install -w

      - name: Build schema package
        run: pnpm --filter @gcg/schema build

      - name: Build HMI UI
        run: pnpm --filter @gcg/hmi-ui build

      - name: Stage HMI bundle to garmin-bundle/web
        run: pnpm --filter @gcg/hmi-ui deploy:web

      - name: Prepare configurator deployment package (prebuild)
        run: pnpm --filter @gcg/web-configurator prebuild

      - name: Build web-configurator (skip prebuild copy)
        run: pnpm --filter @gcg/web-configurator build:skip-prebuild

      - name: Type-check all packages
        run: pnpm -r type-check

      - name: Validate no static value bindings in exported artifacts
        run: node scripts/check-no-static-bindings.js
