name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Type check
        run: pnpm type-check

      - name: Build packages (excluding web-configurator)
        run: pnpm -r --filter "!@gcg/web-configurator" build

      - name: Build web-configurator (skip prebuild)
        run: pnpm --filter @gcg/web-configurator run build:skip-prebuild

      - name: Run tests
        run: pnpm test
